#!/bin/sh
set -e

# If secret_id_key is mounted here, it must  be owned by tord
chown -Rv tord:tord /home/tord/

echo "========================================================"
# display torrc and os-version in log
cat /etc/tor/torrc
echo "========================================================"
cat /etc/os-release
echo "========================================================"

# Run tor as regular user (as set in torrc)
exec /usr/bin/tor -f /etc/tor/torrc
